version: "3.9"
services:
  scrapy:
    build: scrapy
    env_file: ./postgres-config
    depends_on:
      - "database"
    networks:
      - scrapy-database
    secrets:
      - postgres-password
    restart: on-failure

  database:
    image: postgres
    env_file: ./postgres-config
    secrets:
      - postgres-password
    networks:
      - scrapy-database
    volumes:
      - pgdata:/var/lib/postgresql/data

secrets:
  postgres-password:
    file: ./postgres-password

networks:
  scrapy-database:

volumes:
  pgdata:
