version: "3.9"
services:
  scrapy:
    build: scrapy
    env_file: ./postgres-config
    depends_on:
      - "database"
    networks:
      - scrapy-database
    secrets:
      - postgres-password
    restart: on-failure

  windguru-server:
    build: windguru/server
    env_file: ./postgres-config
    depends_on:
      - "database"
    networks:
      - windguru-server-database
      - windguru-client
    secrets:
      - postgres-password
    restart: on-failure

  windguru-scraper:
    build: windguru/scraper
    depends_on:
      - "windguru-server"
    networks:
      - windguru-client
    restart: on-failure

  database:
    image: postgres
    env_file: ./postgres-config
    secrets:
      - postgres-password
    networks:
      - scrapy-database
      - windguru-server-database
    volumes:
      - pgdata:/var/lib/postgresql/data

secrets:
  postgres-password:
    file: ./postgres-password

networks:
  scrapy-database:
  windguru-server-database:
  windguru-client:

volumes:
  pgdata:
